name = "cnzrfrmwrkweb"
compatibility_date = "2024-12-23"

# This tells Wrangler to upload your built frontend files
[assets]
directory = "./public" 

# Environment variables
[vars]
NODE_ENV = "production"

routes = [
  { pattern = "cnzr.biz.id", custom_domain = true }
]
